const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),solc=require('solc');
const {ethers}=require('ethers'),ganache=require('ganache');
const root=path.resolve(__dirname,'..');
const source=fs.readFileSync(path.join(root,'src/EMUERv2.sol'),'utf8');
const input={language:'Solidity',sources:{'EMUERv2.sol':{content:source}},settings:{optimizer:{enabled:true,runs:200},evmVersion:'shanghai',outputSelection:{'*':{'*':['abi','evm.bytecode.object','evm.deployedBytecode.object']}}}};
const out=JSON.parse(solc.compile(JSON.stringify(input),{import:p=>{try{return{contents:fs.readFileSync(require.resolve(p),'utf8')}}catch(e){return{error:e.message}}}}));
const errors=(out.errors||[]).filter(e=>e.severity==='error');assert.equal(errors.length,0,JSON.stringify(errors));
const artifact=out.contracts['EMUERv2.sol'].EMUERv2;
fs.mkdirSync(path.join(root,'artifacts'),{recursive:true});
fs.writeFileSync(path.join(root,'artifacts/EMUERv2.json'),JSON.stringify({compiler:solc.version(),settings:input.settings,...artifact},null,2));
(async()=>{
 const gp=ganache.provider({logging:{quiet:true},chain:{hardfork:'shanghai',time:new Date('2026-09-30T14:59:55Z')},wallet:{totalAccounts:4}});
 const provider=new ethers.BrowserProvider(gp);provider.pollingInterval=10;
 const accounts=gp.getInitialAccounts();const keys=Object.values(accounts).map(x=>x.secretKey);
 const admin=new ethers.Wallet(keys[0]),alice=new ethers.Wallet(keys[1]),bob=new ethers.Wallet(keys[2]);
 const adminTx=await provider.getSigner(0),aliceTx=await provider.getSigner(1),bobTx=await provider.getSigner(2);
 const c=await new ethers.ContractFactory(artifact.abi,artifact.evm.bytecode.object,adminTx).deploy(admin.address,86400);await c.waitForDeployment();
 const addr=await c.getAddress(), chainId=(await provider.getNetwork()).chainId;
 const domain={name:'Emuer',version:'2',chainId,verifyingContract:addr};
 const rewardTypes={Reward:[{name:'claimId',type:'bytes32'},{name:'recipient',type:'address'},{name:'totalAmount',type:'uint256'},{name:'deadline',type:'uint256'}]};
 const orderTypes={Order:[{name:'orderId',type:'bytes32'},{name:'productId',type:'bytes32'},{name:'buyer',type:'address'},{name:'price',type:'uint256'},{name:'deadline',type:'uint256'}]};
 const unit=ethers.parseEther, id=ethers.id, sent=async x=>await (await x).wait();
 const fail=async fn=>assert.rejects(async()=>{const tx=await fn();if(tx.wait)await tx.wait()});
 assert.equal(await c.totalSupply(),unit('10000000'));assert.equal(await c.balanceOf(admin.address),unit('10000000'));
 assert.equal(await c.treasury(),admin.address);console.log('PASS fixed 10m supply minted only to configured treasury');
 await fail(()=>c.connect(admin).transfer(alice.address,1));await fail(()=>c.connect(aliceTx).approve(bob.address,1));console.log('PASS free transfers and approvals disabled for all');
 const deadline=2_000_000_000;
 const early=id('early'),earlySig=await admin.signTypedData(domain,rewardTypes,{claimId:early,recipient:alice.address,totalAmount:1n,deadline});
 await fail(()=>c.connect(aliceTx).claimReward(early,1n,deadline,earlySig));
 await gp.request({method:'evm_increaseTime',params:[10]});await gp.request({method:'evm_mine',params:[]});console.log('PASS rewards cannot start before 2026-10-01 00:00 JST');
 const badClaim=id('bad'),badSig=await bob.signTypedData(domain,rewardTypes,{claimId:badClaim,recipient:alice.address,totalAmount:1n,deadline});
 await fail(()=>c.connect(aliceTx).claimReward(badClaim,1n,deadline,badSig));console.log('PASS unauthorized reward signature rejected');
 const c1=id('cap-fill'), total1=unit('415999'); const sig1=await admin.signTypedData(domain,rewardTypes,{claimId:c1,recipient:alice.address,totalAmount:total1,deadline});
 await sent(c.connect(aliceTx).claimReward(c1,total1,deadline,sig1));assert.equal(await c.balanceOf(alice.address),total1);
 const c2=id('split'),total2=unit('10'),sig2=await admin.signTypedData(domain,rewardTypes,{claimId:c2,recipient:alice.address,totalAmount:total2,deadline});
 await sent(c.connect(aliceTx).claimReward(c2,total2,deadline,sig2));assert.equal(await c.claimPaid(c2),unit('1'));
 await fail(()=>c.connect(aliceTx).claimReward(c2,total2,deadline,sig2));console.log('PASS actual October payouts capped at 416,000 with partial claim');
 await gp.request({method:'evm_increaseTime',params:[31*86400]});await gp.request({method:'evm_mine',params:[]});
 await sent(c.connect(aliceTx).claimReward(c2,total2,deadline,sig2));assert.equal(await c.claimPaid(c2),total2);console.log('PASS unpaid remainder claimable in next JST calendar month');
 await fail(()=>c.connect(aliceTx).claimReward(c2,total2,deadline,sig2));console.log('PASS completed reward cannot replay');
 const revoked=id('revoked'),revSig=await admin.signTypedData(domain,rewardTypes,{claimId:revoked,recipient:alice.address,totalAmount:unit('1'),deadline});
 await sent(c.revokeClaim(revoked));await fail(()=>c.connect(aliceTx).claimReward(revoked,unit('1'),deadline,revSig));console.log('PASS unpaid authorization can be revoked without recovering user funds');
 const oid=id('order-1'),pid=id('event-1'),price=unit('2');const osig=await admin.signTypedData(domain,orderTypes,{orderId:oid,productId:pid,buyer:alice.address,price,deadline});
 const treasuryBefore=await c.balanceOf(admin.address);await sent(c.connect(aliceTx).exchange(oid,pid,price,deadline,osig));assert.equal(await c.balanceOf(admin.address),treasuryBefore+price);console.log('PASS signed eligible exchange returns full price to treasury');
 assert.equal(await c.reservedForRefunds(),price);console.log('PASS unfulfilled exchange price is reserved against reward payouts');
 await fail(()=>c.connect(aliceTx).exchange(oid,pid,price,deadline,osig));console.log('PASS order replay rejected');
 await fail(()=>c.connect(bobTx).exchange(id('other-order'),pid,price,deadline,osig));console.log('PASS signed quote cannot be used by another wallet');
 const pausedOrder=id('paused-order');const pausedSig=await admin.signTypedData(domain,orderTypes,{orderId:pausedOrder,productId:pid,buyer:alice.address,price,deadline});
 await sent(c.pause());await fail(()=>c.connect(aliceTx).exchange(pausedOrder,pid,price,deadline,pausedSig));
 const aliceBefore=await c.balanceOf(alice.address);await sent(c.refundExchange(oid));assert.equal(await c.balanceOf(alice.address),aliceBefore+price);console.log('PASS full refund to original buyer works while paused');
 assert.equal(await c.reservedForRefunds(),0n);
 await fail(()=>c.refundExchange(oid));console.log('PASS refund replay rejected');
 await sent(c.unpause());
 const oid2=id('order-fulfilled'),osig2=await admin.signTypedData(domain,orderTypes,{orderId:oid2,productId:pid,buyer:alice.address,price,deadline});
 await sent(c.connect(aliceTx).exchange(oid2,pid,price,deadline,osig2));await sent(c.markExchangeFulfilled(oid2));
 assert.equal(await c.reservedForRefunds(),0n);await fail(()=>c.refundExchange(oid2));console.log('PASS fulfilled exchange releases reserve and cannot use operator-failure refund');
 assert.equal(await c.totalSupply(),unit('10000000'));console.log('PASS claims, exchange and refund never mint or burn');
 const result={status:'passed',count:16,tests:'See test/v2-policy.cjs console output',compiler:solc.version(),network:'Local Ganache only; no production deployment'};
 fs.writeFileSync(path.join(root,'artifacts/v2-test-results.json'),JSON.stringify(result,null,2));await gp.disconnect();
})().catch(e=>{console.error(e);process.exit(1)});
